[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --headed

markers =
    api: API тесты
    ui: UI тесты
    smoke: быстрые тесты для проверки что всё живо
    regression: полный прогон